### ISSUE TITLE
Going directly to a line fails

### ISSUE THREAD

**Issue by nihaals** [codecov/codecov-browser-extension#36]
For example:
- https://github.com/codecov/example-python/blob/main/app/calculator.py works
- https://github.com/codecov/example-python/blob/main/app/calculator.py#L1 doesn't

This is because the API request includes the fragment:
`GET https://api.codecov.io/api/v2/github/codecov/repos/example-python/report?path=app/calculator.py#L1&branch=main`

**Comment by anukul** [comment]
Thanks for filing the issue. I updated the URL parsing logic to accommodate self hosted providers in #33, and that should fix this as well. We can verify and close this issue once that's released.

**Comment by anukul** [comment]
Fixed :)
